apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-admin-deployment
  namespace: recipes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-admin
  template:
    metadata:
      labels:
        app: api-admin
    spec:
      containers:
        - name: api-admin
          image: recipes-symfony:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: prod
            - name: APP_DEBUG
              value: '0'
            - name: APP_SECRET
              value: recipes-app-secret
            - name: DB_HOST
              value: mysql-service
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: recipesdb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
