apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: recipes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: recipes-angular:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
